version: '2.2'

services:
  claude_pimcore_db:
    extends:
      file: common.yml
      service: claude_pimcore_db
    ports:
      - 10000:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariapwd
    command: mysqld --innodb-large-prefix=ON --innodb-file-format=barracuda
    networks:
      - proxy

  claude_pimcore_php-fpm:
    extends:
      file: common.yml
      service: claude_pimcore_php-fpm
    build:
      args:
        phpini: php_prod.ini
    environment:
      XDEBUG_CONFIG: "client_host=10.0.3.15"
      PHP_IDE_CONFIG: serverName=pimcore
    links:
      - claude_pimcore_db
    networks:
      - proxy

  claude_pimcore_nginx:
    extends:
      file: common.yml
      service: claude_pimcore_nginx
    container_name: claude_pimcore_nginx
    build:
      args:
        nginxconf: nginx_prod.conf
    depends_on:
      - claude_pimcore_php-fpm
    networks:
      - proxy

  claude_pimcore_redis:
    extends:
      file: common.yml
      service: claude_pimcore_redis

networks:
  proxy:
    external: true
